[[constraint]]
  name = "github.com/openzipkin/zipkin-go"
  version = "0.1.1"
  
[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"
  
[[constraint]]
  name = "github.com/boltdb/bolt"
  version = "1.3.1"

[prune]
  go-tests = true
  unused-packages = true  